// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odezyvfrhrypqwcizatv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZXp5dmZyaHJ5cHF3Y2l6YXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNjM0NTIsImV4cCI6MjA2OTgzOTQ1Mn0.Xead-zUPr523CzQUTZTcFYo2Sa1w76OzuUDZDpERtcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});